kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: model-store-claim
spec:
  storageClassName: managed-premium
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi