apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: modelStoreClaim
spec:
  storageClassName: managed-premium
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
