#!/bin/bash

echo "                      =============================================="
echo "                      If you are within a conda env please deactivate it and come back"
echo "                      If you don't want to proceed kill this script in the next 10 seconds!"
echo "                      =============================================="

echo "Cleaning up state"
# uninstall any global installations
pip uninstall --yes torchserve
pip uninstall --yes torch-model-archiver

if frontend/gradlew.bat -p frontend clean build;
  then
  echo "Frontend build suite execution successful"
else
  echo "Frontend build suite execution failed!!! Check logs for more details"
  exit 1
fi

pip install .

echo $PWD
cd model-archiver
if pip install .;
then
  echo "Successfully installed torch-model-archiver"
else
  echo "torch-model-archiver installation failed"
  exit 1
fi
cd ..

rm -rf ts/__pycache__/
rm -rf ts/metrics/__pycache__/
rm -rf ts/protocol/__pycache__/
rm -rf ts/utils/__pycache__/
rm -rf frontend/modelarchive/build
rm -rf frontend/server/build